// <auto-generated />
using System;
using ClosedServices_Admin.Data;
using ClosedServices_Admin.Data.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClosedServices_Admin.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("closedservices")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "closedservices", "service_type", new[] { "schools", "libraries" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<ServiceType>("ServiceType")
                        .HasColumnType("service_type")
                        .HasColumnName("service_type");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("SourceDataId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_data_id");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services", "closedservices");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.ServiceOperatingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notes");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_time");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_operating_days");

                    b.HasIndex("ServiceId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_service_operating_days_service_id_day_of_week");

                    b.ToTable("service_operating_days", "closedservices");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.ServiceStatusUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClosureState")
                        .HasColumnType("integer")
                        .HasColumnName("closure_state");

                    b.Property<Instant>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Instant?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_external_user_id");

                    b.HasKey("Id")
                        .HasName("pk_service_status_updates");

                    b.HasIndex("ServiceId", "UpdatedAt")
                        .HasDatabaseName("ix_service_status_updates_service_id_updated_at");

                    b.ToTable("service_status_updates", "closedservices");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.UserServicePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_user_id");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<ServiceType?>("ServiceType")
                        .HasColumnType("service_type")
                        .HasColumnName("service_type");

                    b.HasKey("Id")
                        .HasName("pk_user_service_permissions");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("ix_user_service_permissions_external_user_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_user_service_permissions_service_id");

                    b.HasIndex("ExternalUserId", "ServiceId")
                        .HasDatabaseName("ix_user_service_permissions_external_user_id_service_id");

                    b.HasIndex("ExternalUserId", "ServiceType")
                        .HasDatabaseName("ix_user_service_permissions_external_user_id_service_type");

                    b.ToTable("user_service_permissions", "closedservices", t =>
                        {
                            t.HasCheckConstraint("ck_userservicepermission_target", "(service_id IS NOT NULL AND service_type IS NULL)\r\nOR (service_id IS NULL AND service_type IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.ServiceOperatingDay", b =>
                {
                    b.HasOne("ClosedServices_Admin.Data.Models.Service", "Service")
                        .WithMany("OperatingDays")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_operating_days_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.ServiceStatusUpdate", b =>
                {
                    b.HasOne("ClosedServices_Admin.Data.Models.Service", "Service")
                        .WithMany("StatusUpdates")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_status_updates_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.UserServicePermission", b =>
                {
                    b.HasOne("ClosedServices_Admin.Data.Models.Service", "Service")
                        .WithMany("Permissions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_service_permissions_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ClosedServices_Admin.Data.Models.Service", b =>
                {
                    b.Navigation("OperatingDays");

                    b.Navigation("Permissions");

                    b.Navigation("StatusUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
